### ISSUE TITLE
Reference to non-existent field 'validposition'.

### ISSUE THREAD

**Issue by 3835** [JorgeGT/PlotRTL1090#3]
I try to run your script, but when I select them all below the break and press "Evaluate Selection" i got this  error:
`Reference to non-existent field 'validposition'.`
I use Matlab 2014b and Windows XP (precompiled mex matlab-json from christianpanton github) and I tested PlotRTL1090 on Mac OS X Mavericks with matalb-json compiled by me, and I got the same error (the same version Matlab). 

Any ideas what is wrong?

**Comment by JorgeGT** [comment]
I can't seem to duplicate the issue, the code runs without error in my system (Windows 8.1 x64, MATLAB r2014b). The field `validposition` should be in the `planes` cell structure, for example:

```
 >> planes{3}

ans = 
          hex: '40643d'
       squawk: '5364'
       flight: 'EZY29TK '
          lat: 38.9042
          lon: -1.0479
validposition: 1
     altitude: 36025
    vert_rate: 0
        track: 52
   validtrack: 1
        speed: 476
     messages: 81
         seen: 0
```

Is this structure being generated correctly? Have you tested the output of your dump1090 server, by accessing `http://yourserverIP:8080/data.json` and looking to the json file? It should be something like this and have the `validposition` field:

```
[
{"hex":"4ca767", "squawk":"0000", "flight":"RYR704W ", "lat":38.966354, "lon":-0.824990,    "validposition":1, "altitude":23000,  "vert_rate":0,"track":334, "validtrack":1,"speed":384, "messages":29,  "seen":4},
{"hex":"4ca566", "squawk":"0000", "flight":"", "lat":0.000000, "lon":0.000000, "validposition":0, "altitude":38000,  "vert_rate":0,"track":70, "validtrack":1,"speed":467, "messages":4, "seen":122}
]
```

Try this and let's see if we can fix the error! =)

**Comment by 3835** [comment]
My `planes`:

```
>> planes{1}

ans = 

         hex: '4ca916'
      flight: 'RYR1063 '
         lat: 51.3153
         lon: 16.7336
    altitude: 36000
       track: 249
       speed: 436
```

and http://myserver:8080/data.json

```
[
{"hex":"3c49a6", "flight":"BER2543 ", "lat":51.152623, "lon":16.809540, "altitude":40000, "track":307, "speed":369},
{"hex":"424052", "flight":"AFL2462 ", "lat":51.584302, "lon":17.427826, "altitude":34025, "track":246, "speed":436},
{"hex":"4ca8e5", "flight":"RYR14MA ", "lat":52.297808, "lon":15.952619, "altitude":14750, "track":97, "speed":330},
{"hex":"4bcca5", "flight":"SXS5G   ", "lat":51.447625, "lon":16.562881, "altitude":35000, "track":147, "speed":548},
{"hex":"3c720a", "flight":"BER7493 ", "lat":51.602830, "lon":15.828781, "altitude":34950, "track":306, "speed":363},
{"hex":"4baa0a", "flight":"THY3ZS  ", "lat":51.680013, "lon":15.998383, "altitude":36000, "track":297, "speed":349},
{"hex":"49d092", "flight":"CSA6KG  ", "lat":52.392334, "lon":15.764999, "altitude":39000, "track":9, "speed":373},
{"hex":"471f7c", "flight":"WZZ5BL  ", "lat":52.289978, "lon":16.349945, "altitude":38025, "track":276, "speed":392},
{"hex":"461f30", "flight":"FIN4DW  ", "lat":52.462143, "lon":16.862869, "altitude":38975, "track":33, "speed":389},
{"hex":"49d095", "flight":"CSA909  ", "lat":51.158861, "lon":15.401306, "altitude":32425, "track":244, "speed":430}
]
```

It's weird, my data.json file looks totally different than yours. But dump1090 map works fine.

**Comment by JorgeGT** [comment]
Damn, I think it's my fault - I'm actually using [MalcolmRobb's forked version of dump1090](https://github.com/MalcolmRobb/dump1090), maybe that's the problem! I wasn't aware of the difference in the json file =/

**Comment by 3835** [comment]
I used [antirez version of dump1090](https://github.com/antirez/dump1090). Now I install MalcolmRobb's fork and everything works fine. Thanks for help!

**Comment by JorgeGT** [comment]
No problem! Be sure to share interesting results! ;)
